Author Credit
RIT-Crowd-Comic/site-content pull request #206
Opened 2024-08-06 20:57 UTC by BlckHawker

Added author credit to read page
- Clicking on the profile picture will show more info (current just when the panel set was created)
- Refactored `InfoBox` and  `InfoBtn` to handle its visibility

2024-08-06 21:36 UTC, 4rt3ry requested changes

2024-08-06 21:36 UTC, 4rt3ry commented on src/components/ReadPage.tsx
Created date is invalid
![image](https://github.com/user-attachments/assets/d4c4f5f4-1d1e-43ad-bb4a-306a838a80df)

2024-08-06 21:36 UTC, 4rt3ry commented on src/components/Signature.tsx
Add CSS on hover
```css
cursor: pointer;
```

2024-08-07 14:36 UTC, BlckHawker commented on src/components/ReadPage.tsx
I'm not getting that error. Make sure you backend is up to date with main. If the error still occurs, would you mind printing out what `author?.created_at` is for you on line 186 of the read page?

2024-08-07 17:03 UTC, 4rt3ry commented on src/components/ReadPage.tsx
yep, it works

2024-08-07 17:15 UTC, merged